spring:
  application:
    name: elasticsearch-study
  
  elasticsearch:
    uris: http://localhost:9200
    connection-timeout: 5s
    socket-timeout: 30s
    
  data:
    elasticsearch:
      client:
        reactive:
          endpoints: localhost:9200
          use-ssl: false

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ad-statistics-consumer
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.study.essearch.dto
        spring.json.type.mapping: AdStatisticsMessage:com.study.essearch.dto.AdStatisticsMessage
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


logging:
  level:
    org.springframework.data.elasticsearch: DEBUG
    org.elasticsearch: DEBUG
    org.springframework.kafka: INFO